[tool.poetry]
name = "dsutil"
version = "1.2.0"
description = "Danny's Python utility scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"
packages = [{include = "dsutil", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
"path.py" = "^12.5.0"
halo = "^0.0.31"
natsort = "^8.4.0"
pathlib = "^1.0.1"
pygments = "^2.18.0"
requests = "^2.32.3"
send2trash = "^1.8.3"
soundfile = "^0.12.1"
termcolor = "^2.5.0"
textual = "<0.86.0,>=0.85.2"
tzdata = "^2024.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.13.0"
ruff = "^0.7.3"
types-requests = "^2.32.0.20241016"
types-send2trash = "^1.8.2.7"

[tool.poetry.scripts]
code-configs = "dsutil.configs:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
