[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "dsutil"
description = "Danny's Python utility scripts"
version = "1.5.9"
authors = [
    { name = "Danny Stewart", email = "danny@stewart.cc" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "halo>=0.0.31",
    "natsort>=8.4.0",
    "path.py>=12.5.0",
    "pathlib>=1.0.1",
    "pygments>=2.18.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "send2trash>=1.8.3",
    "soundfile>=0.12.1",
    "termcolor>=2.5.0",
    "textual>=0.89.1",
    "tzdata>=2024.2",
]

[project.optional-dependencies]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.8.2",
    "types-requests>=2.32.0.20241016",
    "types-send2trash>=1.8.2.7",
]

[project.scripts]
code-configs = "dsutil.configs.code_configs:main"

[tool.hatch.version]
path = "src/dsutil/__init__.py"

[tool.hatch.build.targets.wheel]
packages = [
    "src/dsutil",
]
