[tool.poetry]
name = "dsutil"
version = "1.0.0"
description = "Danny's Python utility scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"
packages = [{include = "dsutil", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
"path.py" = "^12.5.0"
argparse = "^1.4.0"
halo = "^0.0.31"
natsort = "^8.4.0"
pathlib = "^1.0.1"
pygments = "^2.18.0"
requests = "^2.32.2"
Send2Trash = "^1.8.3"
soundfile = "^0.12.1"
termcolor = "^2.4.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
ruff = "^0.7.1"
types-requests = "^2.32.0.20240523"
types-send2trash = "^1.8.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
