[tool.poetry]
name = "dsutil"
version = "0.3.0"
description = "Danny's Python utility scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
"path.py" = "^12.5.0"
argparse = "^1.4.0"
azure-storage-blob = "^12.20.0"
colorama = "^0.4.6"
distro = "^1.9.0"
halo = "^0.0.31"
inquirer = "^3.2.4"
mutagen = "^1.47.0"
natsort = "^8.4.0"
numpy = "^1.26.4"
paramiko = "^3.4.0"
pathlib = "^1.0.1"
Pillow = "^10.3.0"
pycountry = "^23.12.11"
pydub = "^0.25.1"
pygments = "^2.18.0"
pyperclip = "^1.8.2"
pyreadline = "^2.1"
python-dotenv = "^1.0.1"
readchar = "^4.1.0"
requests = "^2.32.2"
SciPy = "^1.13.1"
scp = "^0.15.0"
Send2Trash = "^1.8.3"
soundfile = "^0.12.1"
telethon = "^1.35.0"
termcolor = "^2.4.0"
tomlkit = "^0.13.2"
tqdm = "^4.66.4"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
ruff = "^0.7.1"
setuptools = "^70.0.0"
types-paramiko = "^3.4.0.20240423"
types-pillow = "^10.2.0.20240520"
types-requests = "^2.32.0.20240523"
types-send2trash = "^1.8.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
