[tool.poetry]
name = "dsutil"
version = "0.1.0"
description = "Danny's Python utility scripts"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
argparse = "^1.4.0"
azure-storage-blob = "^12.19.0"
colorama = "^0.4.6"
distro = "^1.9.0"
halo = "^0.0.31"
inquirer = "^3.1.4"
mutagen = "^1.47.0"
natsort = "^8.4.0"
numpy = "^1.26.2"
paramiko = "^3.4.0"
"path.py" = "^12.5.0"
Pillow = "^10.1.0"
pycountry = "^23.12.11"
pydub = "^0.25.1"
pyperclip = "^1.8.2"
pyreadline = "^2.1"
python-dotenv = "^1.0.0"
readchar = "^4.0.5"
requests = "^2.31.0"
SciPy = "^1.11.4"
scp = "^0.14.5"
Send2Trash = "^1.8.2"
soundfile = "^0.12.1"
telethon = "^1.35.0"
termcolor = "^2.4.0"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
ruff = "^0.3.3"
setuptools = "^69.0.3"
types-paramiko = "^3.4.0.20240311"
types-pillow = "^10.2.0.20240331"
types-requests = "^2.31.0.20240403"
types-send2trash = "^1.8.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [
    ".git",
    ".mypy_cache",
    ".pyenv",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "C", "W"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
ignore_missing_imports = true
